### PR TITLE
Support collection builders in .NET 8+.

### PR DESCRIPTION
**Pull request by oconnor0**

### CODE REVIEW

**Comment by oconnor0** [comment]
Might make sense to drop .NET 6 support. I don't know why I picked that version in the first place. Maybe just to avoid some of the constant "shiny new thing" churn.

**Comment by oconnor0** [comment]
I will conditionally retract my comment about dropping .NET 6 support. At some point, we'll want to support dictionary collection builders when they get added and that might require a newer version of .NET. (Depends on whether or not it's just a compile-time feature.) If that's the case, there's no reason that I can see to require .NET 9+ if .NET 8+ is sufficient.

**Comment by isaksky** [comment]
I think for support we could just follow the Microsoft LTS support schedule if it is getting tedious or costly. So that means after November 12, 2024, we could take off .NET 6.

**Review by isaksky — APPROVED** [review]
Looks good.

**Pull request merged**
